# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tov < Formula
  desc "tmux overseer — TUI tool for monitoring all tmux panes with Claude Code status"
  homepage "https://github.com/magcho/tmux-overview"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/magcho/tmux-overview/releases/download/v1.1.0/tov_1.1.0_darwin_amd64.tar.gz"
      sha256 "c6a01d8e47d89631765418f11cfb927245d88d1cf96837ca37d7a6483d3ef836"

      define_method(:install) do
        bin.install "tov"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/magcho/tmux-overview/releases/download/v1.1.0/tov_1.1.0_darwin_arm64.tar.gz"
      sha256 "04db0acf60ac641201c7e88289b75d5ddb3de17228e3ec1b3e077cde4f96d460"

      define_method(:install) do
        bin.install "tov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/magcho/tmux-overview/releases/download/v1.1.0/tov_1.1.0_linux_amd64.tar.gz"
      sha256 "a793b636ce40feff1db0ec1dc8101600c8c3c7ccf6c388ab09599b84d67e79fb"
      define_method(:install) do
        bin.install "tov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/magcho/tmux-overview/releases/download/v1.1.0/tov_1.1.0_linux_arm64.tar.gz"
      sha256 "34f62449af274f1a1abe422b689f56a1066f400fa4206ca075eca384ced0167a"
      define_method(:install) do
        bin.install "tov"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tov version")
  end
end
