# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tov < Formula
  desc "tmux overseer — TUI tool for monitoring all tmux panes with Claude Code status"
  homepage "https://github.com/magcho/tmux-overview"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/magcho/tmux-overview/releases/download/v1.0.0/tov_1.0.0_darwin_amd64.tar.gz"
      sha256 "be8cb1799dec84f15266c70499d90cba9929964d82b08920d1217072fb0f0b4d"

      define_method(:install) do
        bin.install "tov"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/magcho/tmux-overview/releases/download/v1.0.0/tov_1.0.0_darwin_arm64.tar.gz"
      sha256 "a4c14602ab4843063b0b051541bf2c5548500f128f594b2b8628487ff8776f39"

      define_method(:install) do
        bin.install "tov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/magcho/tmux-overview/releases/download/v1.0.0/tov_1.0.0_linux_amd64.tar.gz"
      sha256 "7257d19aa923bf5746f60176e50b0c06d7e4343808eac07b18f56440acdd5325"
      define_method(:install) do
        bin.install "tov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/magcho/tmux-overview/releases/download/v1.0.0/tov_1.0.0_linux_arm64.tar.gz"
      sha256 "799f39f6293c103ac9e20964a32cecc41a941ae8a4e23a334f84a5c6d237aefa"
      define_method(:install) do
        bin.install "tov"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tov version")
  end
end
